name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: yangqi.co/typecho
          path: typecho
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: https://github.com/wehaox/Typecho-Butterfly
          path: Butterfly
      - name: list
        run: |
          tree -a