name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: "${{ matrix.extension }} (PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extension:
          - amqp
          - apcu
          - bcmath
        php-version:
          - "8.4"
        operating-system:
          - "ubuntu-latest"
          - "macos-14"
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
