on:
  workflow_call:

env:
  ALIYUNCS_USERNAME: "12334"

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to AliyunCS
        uses: docker/login-action@v3
        with:
          registry: registry.aliyuncs.com
          username: ${{ secrets.ALIYUNCS_USERNAME }}
          password: ${{ secrets.ALIYUNCS_PASSWORD }}