on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
      username:
        required: true
        type: string
      password:
        required: true
        type: string

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: |
          set -eux
          echo "registry: ${{ inputs.registry }}"
          echo "image: ${{ inputs.image }}"
          echo "username: ${{ inputs.username }}"
          echo "password: ${{ inputs.password }}"
          
          echo ${{ secrets.RSYNC_HOST }}