on:
  workflow_call:
    inputs:
      registries:
        required: true
        type: string

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: |
          set -eux
          echo ${{ inputs.registries }}
          echo ${{ secrets.RSYNC_HOST }}