on:
  workflow_call:
    inputs:
      registries:
        required: true
        type: string

jobs:
  docker-login:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.registries) }}
    steps:
      - name: info
        run: |
          set -eux
          echo "registry: ${{ matrix.registry }}"
          echo "image: ${{ matrix.image }}"
          echo "username: ${{ matrix.username }}"
          echo "password: ${{ matrix.password }}"
          
          echo ${{ secrets.RSYNC_HOST }}