name: tests

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

env:
  EXT_CONFIG: build/config/ext.yaml
  SUITE_CONFIG: build/config/suite.yaml

jobs:
  init:
    name: Query Config
    runs-on: "ubuntu-latest"
    outputs:
      config: ${{ steps.query-config.outputs.config }}
      registries: ${{ steps.query-config.outputs.registries }}
    steps:
      - name: Query Config
        id: query-config
        shell: bash
        run: |
          set -eux
          config='{"distro": ["debian", "alpine"], "suite": ["swoole"], "version": ["8.3.16"]}'
          
          echo config=$config >> $GITHUB_OUTPUT
          
          registries='[{"registry":"docker.io","image":"iiqi/php","username":"DOCKERHUB_USERNAME","password":"DOCKERHUB_TOKEN"},{"registry":"aliyun.com","image":"iiqi/php","username":"ALIYUNCS_USERNAME","password":"ALIYUNCS_PASSWORD"}]'

          echo registries=$registries >> $GITHUB_OUTPUT

  build:
    name: Build PHP ${{ matrix.version }}-${{ matrix.suite }}-${{ matrix.distro }}
    runs-on: "ubuntu-latest"
    needs:
      - init
    strategy:
      matrix:
        distro: ["debian", "alpine"]
        suite: ["swoole"]
        version: ["8.3.16"]
      fail-fast: false
    steps:

      - name: Config
        id: config
        shell: bash
        run: |
          DISTRO=${{ matrix.distro }}
          SUITE=${{ matrix.suite }}
          VERSION=${{ matrix.version }}

      - name: Print Config
        shell: bash
        run: |
          echo "distro: ${{ matrix.distro }}"
          echo "suite: ${{ matrix.suite }}"
          echo "version: ${{ matrix.version }}"

  sync:
    name: Sync ${{ matrix.registry }}
    needs:
      - build
    strategy:
      matrix:
        include: ${{ fromJSON(needs.init.outputs.registries) }}
    uses: ./.github/workflows/sync.yml
    secrets: inherit
    with:
      registry: ${{ matrix.registry }}
      image: ${{ matrix.image }}
      username: ${{ matrix.username }}
      password: ${{ matrix.password }}