name: tests

on:
  push:
  workflow_dispatch:

jobs:
  init:
    name: Fetch latest PHP version
    runs-on: "ubuntu-latest"
    outputs:
      config: ${{ steps.fetch.outputs.config }}
    steps:
      - name: Fetch version info
        id: fetch
        run: |
          printf 'config=[{"name":"master","rev":"master","patch":"84"}]' >> $GITHUB_OUTPUT

  linuxtests:
    name: Linux tests for PHP ${{ matrix.name }}
    runs-on: "ubuntu-latest"
    needs:
      - init
    strategy:
      matrix:
        include: ${{ fromJSON(needs.init.outputs.config) }}
      max-parallel: 3
      fail-fast: false
    steps:
      - name: Print Config
        shell: bash
        run: |
          echo "name: ${{ matrix.name }}"
          echo "rev: ${{ matrix.rev }}"
          echo "patch: ${{ matrix.patch }}"