name: tests

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

env:
  EXT_CONFIG: build/config/ext.yaml
  SUITE_CONFIG: build/config/suite.yaml

jobs:
  init:
    name: Query Config
    runs-on: "ubuntu-latest"
    outputs:
      config: ${{ steps.query-config.outputs.config }}
    steps:
      - name: Query Config
        id: query-config
        shell: bash
        run: |
          config='{"distro": ["debian", "alpine"], "suite": ["swoole"], "version": ["8.3.16"]}'
          
          echo config=$config >> $GITHUB_OUTPUT
  login:
    name: Login
    uses: ./.github/workflows/docker-login.yml
    secrets: inherit

  build:
    name: Build PHP ${{ matrix.version }}-${{ matrix.suite }}-${{ matrix.distro }}
    runs-on: "ubuntu-latest"
    needs:
      - init
    strategy:
      matrix:
        distro: ["debian", "alpine"]
        suite: ["swoole"]
        version: ["8.3.16"]
      fail-fast: false
    steps:

      - name: Config
        id: config
        shell: bash
        run: |
          DISTRO=${{ matrix.distro }}
          SUITE=${{ matrix.suite }}
          VERSION=${{ matrix.version }}

      - name: Print Config
        shell: bash
        run: |
          echo "distro: ${{ matrix.distro }}"
          echo "suite: ${{ matrix.suite }}"
          echo "version: ${{ matrix.version }}"
          echo "===================env=================="
          env
