name: tests

on:
  push:
  workflow_dispatch:

jobs:
  init:
    name: Fetch latest PHP version
    runs-on: "ubuntu-latest"
    outputs:
      config: ${{ steps.fetch.outputs.config }}
    steps:
      - name: Fetch version info
        id: fetch
        run: |
          printf 'config={"distro":["debian","alpine"],"suite":["fpm","swoole"],"version":["8.0.30","8.1.31","8.2.27","8.3.16","8.4.3"]}' >> $GITHUB_OUTPUT

  linuxtests:
    name: Linux tests for PHP ${{ matrix.suite }}
    runs-on: "ubuntu-latest"
    needs:
      - init
    strategy:
      matrix: ${{ fromJSON(needs.init.outputs.config) }}
      max-parallel: 3
      fail-fast: false
    steps:
      - name: Print Config
        shell: bash
        run: |
          echo "distro: ${{ matrix.distro }}"
          echo "suite: ${{ matrix.suite }}"
          echo "version: ${{ matrix.version }}"